### ISSUE TITLE
Conflict with Symfony core collectors

### ISSUE THREAD

**Issue by stof** [Elao/WebProfilerExtraBundle#50]
The routing data collector implemented in the bundle uses the same name than the core one, so it will replace it. This is a bad idea IMO.
thus, the implementation of your RoutingDataCollector is a performance killer by reloading the route collection on each request (which is something we avoided in the core one)

**Comment by stof** [comment]
The actual need is not to rename services (this is not where the conflicts are) but the data collectors.

and the Twig collector will also conflict in Symfpny 2.7: https://github.com/symfony/symfony/pull/13428

Having to disable things in this bundle explicitly to avoid loosing Symfony core features is a bad DX. Can you please change the collector names (prefix them with ``elao_`` for instance)

**Comment by benji07** [comment]
@stof i change the collector name in the PR #61

**Comment by benji07** [comment]
ok, the PR is merged
