### ISSUE TITLE
DEPRECATED

### ISSUE THREAD

**Issue by tubssp** [Elao/WebProfilerExtraBundle#62]
DEPRECATED - The Symfony\Component\Routing\Route::getPattern method is deprecated since version 2.2 and will be removed in 3.0. Use the getPath() method instead. 

in File /vendor/elao/web-profiler-extra-bundle/DataCollector/RoutingDataCollector.php
Line 70
'pattern' => $route->getPattern(),
 can you please fix it...

**Comment by benji07** [comment]
@tubssp could you make the PR ?
