### ISSUE TITLE
What about removing dependency to assetic bundle?

### ISSUE THREAD

**Issue by robertfausk** [Elao/WebProfilerExtraBundle#68]
Currently you have to require symfony/assetic-bundle to get this bundle work properly.

The https://github.com/symfony/web-profiler-bundle works without dependeny to assetic. What about removing this dependency in the WebProfilerExtraBundle also?

At least there should be a requirement to symfony/assetic-bundle stated in composer.json.
Without assetic bundle a ServiceNotFoundException will be thrown (You have requested a non-existent service "assetic.asset_manager".) and web profiler extra bundle will not work.

**Comment by benji07** [comment]
we don't require assetic, because you can disable the collector inside the configuration, we don't use assetic for almost a year, and this bundle work fine for us

**Comment by robertfausk** [comment]
Ok, I also found out that you only need to disable assetic via bundles collectors config. Some hint in doc about that would be nice. Shall I send a PR for that?

    web_profiler_extra:
        assetic:
            enabled:        false
            display_in_wdt: false

Another pouint: I didn't test the display of the beautiful icons: https://github.com/Elao/WebProfilerExtraBundle#install-assets
Will they also work without assetic? Or do I have to manually place them in the web folder?

**Comment by benji07** [comment]
that would be nice.

This work without assetic too

**Comment by robertfausk** [comment]
I didn't know yet that ```assets:install``` belongs to FrameworkBundle. All fine now. Thank you:)
