### ISSUE TITLE
Compatibility symfony 2.7

### ISSUE THREAD

**Issue by nicolastiran** [Elao/WebProfilerExtraBundle#71]
Hello,

I have this message with Symfony 2.7 :
Defining the initRuntime() method in an extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended). 

Symfony : 2.7.5
WebProfilerExtraBundle : 2.3-dev

**Comment by benji07** [comment]
I think you have an extension that cause this error.

You could add a var_dump inside the Twig_Environnement class (inside the initRuntime method just before the trigger_error) to see which one cause this error

**Comment by benji07** [comment]
Spring cleaning, If this issue is still relevant, please reopen-it.
