### ISSUE TITLE
Add option to disable showing parameters.yml content

### ISSUE THREAD

**Issue by clytemnestra** [Elao/WebProfilerExtraBundle#73]
Great bundle, but I have a small issue with it. The fact that it displays parameters.yml content. There should be an option to disable showing those contents. Sometimes they contain sensitive data and it might cause trouble. Obviously, the documentation does recommend storing sensitive data somewhere else, but in the development process it is easier to use this file.

What do you think?

**Comment by benji07** [comment]
This bundle should only be used in dev environment (and you must not deploy your app_dev.php file)

**Comment by clytemnestra** [comment]
Obviously, but sometimes there is a public version of the website that is being tested and needs to be debugged with the dev environment.

**Comment by benji07** [comment]
Spring cleaning, If this issue is still relevant, please reopen-it.
