### ISSUE TITLE
Symfony 3.4

### ISSUE THREAD

**Issue by pdias** [Elao/WebProfilerExtraBundle#78]
After upgrading to Symfony 3.4 i have this warning:

> User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "Elao\WebProfilerExtraBundle\DataCollector\ContainerDataCollector"

Thanks,

Paulo Dias

**Comment by tristanbes** [comment]
There's a PR for that #77

**Comment by benji07** [comment]
@pdias this should be ok, now

**Comment by pdias** [comment]
Yes, it ok now. Thanks.
