### ISSUE TITLE
Symfony4 compatibility

### ISSUE THREAD

**Issue by bobvandevijver** [Elao/WebProfilerExtraBundle#79]
When you're working on a new Symfony 4 project (which uses the new template syntax as default, the following error is thrown after requiring the bundle and disabling its twig support:

```
The profiler template "WebProfilerExtraBundle:Collector:routing.html.twig" for data collector "elao_routing" does not exist.
```

This is due to the fact that the old syntax of `Bundle:Path:To:File.html.twig` is deprecated, which is replaced by the `@Bundle/Path/To/File.html.twig` syntax. If this is not changed, it is not possible to use Symfony 3.4+'s new default_path for overriding template files. See symfony/symfony#25661.

**Comment by benji07** [comment]
@bobvandevijver fixed on the last release thanks to #81 and #80
